[2019-06-18 22:57:10,736: INFO/MainProcess] Connected to redis://localhost:6379//
[2019-06-18 22:57:10,770: INFO/MainProcess] mingle: searching for neighbors
[2019-06-18 22:57:11,831: INFO/MainProcess] mingle: all alone
[2019-06-18 22:57:11,843: INFO/MainProcess] celery@mywealthanalyst ready.
[2019-06-18 23:00:00,028: INFO/MainProcess] Received task: cron_update_live_prices[1c1fea44-e83b-4bf8-8176-b5be5de91580]  
[2019-06-18 23:00:11,881: INFO/ForkPoolWorker-1] cron_update_live_prices[1c1fea44-e83b-4bf8-8176-b5be5de91580]: Driver started - GET request made
[2019-06-18 23:00:14,379: INFO/ForkPoolWorker-1] cron_update_live_prices[1c1fea44-e83b-4bf8-8176-b5be5de91580]: Live prices updated
[2019-06-18 23:00:14,380: INFO/ForkPoolWorker-1] Task cron_update_live_prices[1c1fea44-e83b-4bf8-8176-b5be5de91580] succeeded in 14.348578207000003s: None
[2019-06-18 23:54:03,750: INFO/MainProcess] Connected to redis://localhost:6379//
[2019-06-18 23:54:03,768: INFO/MainProcess] mingle: searching for neighbors
[2019-06-18 23:54:04,801: INFO/MainProcess] mingle: all alone
[2019-06-18 23:54:04,815: INFO/MainProcess] celery@mywealthanalyst ready.
[2019-06-18 23:55:00,035: INFO/MainProcess] Received task: cron_update_live_prices[1cedc9a2-1bd9-4ec6-a5c5-60dbef0dbe47]  
[2019-06-18 23:55:13,339: INFO/ForkPoolWorker-1] cron_update_live_prices[1cedc9a2-1bd9-4ec6-a5c5-60dbef0dbe47]: Driver started - GET request made
[2019-06-18 23:55:16,127: INFO/ForkPoolWorker-1] cron_update_live_prices[1cedc9a2-1bd9-4ec6-a5c5-60dbef0dbe47]: Live prices updated
[2019-06-18 23:55:16,128: INFO/ForkPoolWorker-1] Task cron_update_live_prices[1cedc9a2-1bd9-4ec6-a5c5-60dbef0dbe47] succeeded in 16.090716832s: None
[2019-06-18 23:56:32,152: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/home/mwa_env/lib/python3.6/site-packages/redis/connection.py", line 185, in _read_from_socket
    raise socket.error(SERVER_CLOSED_CONNECTION_ERROR)
OSError: Connection closed by server.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mwa_env/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/home/mwa_env/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/home/mwa_env/lib/python3.6/site-packages/kombu/transport/redis.py", line 1070, in on_readable
    self.cycle.on_readable(fileno)
  File "/home/mwa_env/lib/python3.6/site-packages/kombu/transport/redis.py", line 348, in on_readable
    chan.handlers[type]()
  File "/home/mwa_env/lib/python3.6/site-packages/kombu/transport/redis.py", line 679, in _receive
    ret.append(self._receive_one(c))
  File "/home/mwa_env/lib/python3.6/site-packages/kombu/transport/redis.py", line 690, in _receive_one
    response = c.parse_response()
  File "/home/mwa_env/lib/python3.6/site-packages/redis/client.py", line 3036, in parse_response
    return self._execute(connection, connection.read_response)
  File "/home/mwa_env/lib/python3.6/site-packages/redis/client.py", line 3013, in _execute
    return command(*args)
  File "/home/mwa_env/lib/python3.6/site-packages/redis/connection.py", line 637, in read_response
    response = self._parser.read_response()
  File "/home/mwa_env/lib/python3.6/site-packages/redis/connection.py", line 290, in read_response
    response = self._buffer.readline()
  File "/home/mwa_env/lib/python3.6/site-packages/redis/connection.py", line 224, in readline
    self._read_from_socket()
  File "/home/mwa_env/lib/python3.6/site-packages/redis/connection.py", line 199, in _read_from_socket
    (e.args,))
redis.exceptions.ConnectionError: Error while reading from socket: ('Connection closed by server.',)
[2019-06-18 23:57:58,545: INFO/MainProcess] Connected to redis://localhost:6379//
[2019-06-18 23:57:58,560: INFO/MainProcess] mingle: searching for neighbors
[2019-06-18 23:57:59,588: INFO/MainProcess] mingle: all alone
[2019-06-18 23:57:59,608: INFO/MainProcess] celery@mywealthanalyst ready.
[2019-06-19 00:00:00,031: INFO/MainProcess] Received task: cron_update_live_prices[fa3bbc6b-de6f-4f80-a528-f834760cd651]  
[2019-06-19 00:02:21,312: INFO/ForkPoolWorker-1] cron_update_live_prices[fa3bbc6b-de6f-4f80-a528-f834760cd651]: Driver started - GET request made
[2019-06-19 00:02:22,589: INFO/ForkPoolWorker-1] cron_update_live_prices[fa3bbc6b-de6f-4f80-a528-f834760cd651]: Live prices updated
[2019-06-19 00:02:22,590: INFO/ForkPoolWorker-1] Task cron_update_live_prices[fa3bbc6b-de6f-4f80-a528-f834760cd651] succeeded in 142.556046003s: None
[2019-06-19 00:05:00,093: INFO/MainProcess] Received task: cron_update_live_prices[cbb5a83a-f2b4-40c3-9e09-2de6b53af95d]  
[2019-06-19 00:05:01,990: INFO/ForkPoolWorker-1] cron_update_live_prices[cbb5a83a-f2b4-40c3-9e09-2de6b53af95d]: Live prices updated
[2019-06-19 00:05:01,991: INFO/ForkPoolWorker-1] Task cron_update_live_prices[cbb5a83a-f2b4-40c3-9e09-2de6b53af95d] succeeded in 1.8962519730000054s: None
[2019-06-19 00:10:00,072: INFO/MainProcess] Received task: cron_update_live_prices[66ce3bd9-fb3c-459c-8b2d-04ca49c9a57c]  
[2019-06-19 00:10:02,028: INFO/ForkPoolWorker-1] cron_update_live_prices[66ce3bd9-fb3c-459c-8b2d-04ca49c9a57c]: Live prices updated
[2019-06-19 00:10:02,029: INFO/ForkPoolWorker-1] Task cron_update_live_prices[66ce3bd9-fb3c-459c-8b2d-04ca49c9a57c] succeeded in 1.9552632310000035s: None
[2019-06-19 00:15:00,093: INFO/MainProcess] Received task: cron_update_live_prices[4c3c05d6-bffc-4f26-8fc9-1bc6aefb04d4]  
[2019-06-19 00:15:02,553: INFO/ForkPoolWorker-1] cron_update_live_prices[4c3c05d6-bffc-4f26-8fc9-1bc6aefb04d4]: Live prices updated
[2019-06-19 00:15:02,554: INFO/ForkPoolWorker-1] Task cron_update_live_prices[4c3c05d6-bffc-4f26-8fc9-1bc6aefb04d4] succeeded in 2.4598681099998885s: None
[2019-06-19 00:20:00,085: INFO/MainProcess] Received task: update_historic_from_live_prices[78a2924a-1745-4b72-bc80-5782aa865726]  
[2019-06-19 00:20:00,095: INFO/MainProcess] Received task: cron_update_live_prices[c8f90f5f-8fab-4869-8d62-93d20831fe26]  
[2019-06-19 00:20:00,393: INFO/ForkPoolWorker-1] Task update_historic_from_live_prices[78a2924a-1745-4b72-bc80-5782aa865726] succeeded in 0.30590050599994356s: None
[2019-06-19 00:20:02,045: INFO/ForkPoolWorker-1] cron_update_live_prices[c8f90f5f-8fab-4869-8d62-93d20831fe26]: Live prices updated
[2019-06-19 00:20:02,046: INFO/ForkPoolWorker-1] Task cron_update_live_prices[c8f90f5f-8fab-4869-8d62-93d20831fe26] succeeded in 1.6467094099998576s: None
[2019-06-19 00:25:00,038: INFO/MainProcess] Received task: cron_update_live_prices[75917658-4e34-45ab-9271-2381916c5d73]  
[2019-06-19 00:25:03,660: INFO/ForkPoolWorker-1] cron_update_live_prices[75917658-4e34-45ab-9271-2381916c5d73]: Live prices updated
[2019-06-19 00:25:03,661: INFO/ForkPoolWorker-1] Task cron_update_live_prices[75917658-4e34-45ab-9271-2381916c5d73] succeeded in 3.621286272000134s: None
[2019-06-19 00:30:00,018: INFO/MainProcess] Received task: cron_update_live_prices[543800af-40ee-4c5f-9e5b-013c677fa3fb]  
[2019-06-19 00:30:01,706: INFO/ForkPoolWorker-1] cron_update_live_prices[543800af-40ee-4c5f-9e5b-013c677fa3fb]: Live prices updated
[2019-06-19 00:30:01,707: INFO/ForkPoolWorker-1] Task cron_update_live_prices[543800af-40ee-4c5f-9e5b-013c677fa3fb] succeeded in 1.6871153140000388s: None
