celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/mwa_env/lib/python3.6/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/home/mwa_env/lib/python3.6/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/mwa_env/lib/python3.6/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/mwa_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/admin.py", line 7, in <module>
    from scripts import scrape_livedata_v2
  File "/home/website-build/mywealthanalyst_django/scripts/scrape_livedata_v2.py", line 21, in <module>
    driver = webdriver.Chrome(chrome_options=options)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-51-generic x86_64)

celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/mwa_env/lib/python3.6/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/home/mwa_env/lib/python3.6/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/mwa_env/lib/python3.6/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/mwa_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/admin.py", line 7, in <module>
    from scripts import scrape_livedata_v2
  File "/home/website-build/mywealthanalyst_django/scripts/scrape_livedata_v2.py", line 21, in <module>
    driver = webdriver.Chrome(chrome_options=options)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-51-generic x86_64)

celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/mwa_env/lib/python3.6/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/home/mwa_env/lib/python3.6/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/mwa_env/lib/python3.6/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/mwa_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/admin.py", line 7, in <module>
    from scripts import scrape_livedata_v2
  File "/home/website-build/mywealthanalyst_django/scripts/scrape_livedata_v2.py", line 21, in <module>
    driver = webdriver.Chrome(chrome_options=options)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-51-generic x86_64)

celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/mwa_env/lib/python3.6/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/home/mwa_env/lib/python3.6/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/mwa_env/lib/python3.6/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/home/mwa_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/admin.py", line 7, in <module>
    from scripts import scrape_livedata_v2
  File "/home/website-build/mywealthanalyst_django/scripts/scrape_livedata_v2.py", line 21, in <module>
    driver = webdriver.Chrome(chrome_options=options)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-51-generic x86_64)

[2019-06-11 23:22:06,797: INFO/MainProcess] beat: Starting...
[2019-06-11 23:22:07,235: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
[2019-06-11 23:25:00,157: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
[2019-06-11 23:30:01,830: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
[2019-06-11 23:35:06,049: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
celery beat v4.3.0 (rhubarb) is starting.
__    -    ... __   -        _
LocalTime -> 2019-06-11 23:22:06
Configuration ->
    . broker -> redis://localhost:6379//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)
[2019-06-11 23:38:31,263: INFO/MainProcess] beat: Starting...
[2019-06-11 23:38:31,310: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
[2019-06-11 23:40:00,000: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
[2019-06-11 23:45:00,059: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
[2019-06-11 23:50:00,031: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
celery beat v4.3.0 (rhubarb) is starting.
__    -    ... __   -        _
LocalTime -> 2019-06-11 23:38:31
Configuration ->
    . broker -> redis://localhost:6379//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)
celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/apps.py", line 22, in ready
    driver = webdriver.Chrome(chrome_options=options)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-51-generic x86_64)

celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/apps.py", line 22, in ready
    driver = webdriver.Chrome(chrome_options=options)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-51-generic x86_64)

celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/apps.py", line 22, in ready
    driver = webdriver.Chrome(chrome_options=options)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-51-generic x86_64)

celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/apps.py", line 22, in ready
    driver = webdriver.Chrome(chrome_options=options)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-51-generic x86_64)

[2019-06-11 23:58:03,528: INFO/MainProcess] beat: Starting...
[2019-06-11 23:58:04,442: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
[2019-06-12 00:00:00,666: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
Stale pidfile exists - Removing it.
[2019-06-12 00:01:14,637: INFO/MainProcess] beat: Starting...
[2019-06-12 00:01:14,685: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
celery beat v4.3.0 (rhubarb) is starting.
__    -    ... __   -        _
LocalTime -> 2019-06-12 00:01:14
Configuration ->
    . broker -> redis://localhost:6379//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)
celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/apps.py", line 27, in ready
    page = driver.get('https://au.investing.com/?ref=www')
AttributeError: 'NoneType' object has no attribute 'get'
celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/apps.py", line 27, in ready
    page = driver.get('https://au.investing.com/?ref=www')
AttributeError: 'NoneType' object has no attribute 'get'
celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/apps.py", line 27, in ready
    page = driver.get('https://au.investing.com/?ref=www')
AttributeError: 'NoneType' object has no attribute 'get'
celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/apps.py", line 27, in ready
    page = driver.get('https://au.investing.com/?ref=www')
AttributeError: 'NoneType' object has no attribute 'get'
celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/apps.py", line 32, in ready
    page = driver.get('https://au.investing.com/?ref=www')
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-51-generic x86_64)

celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/apps.py", line 32, in ready
    page = driver.get('https://au.investing.com/?ref=www')
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-51-generic x86_64)

celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/apps.py", line 32, in ready
    page = driver.get('https://au.investing.com/?ref=www')
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/mwa_env/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: session deleted because of page crash
from tab crashed
  (Session info: chrome=74.0.3729.169)
  (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-51-generic x86_64)

[2019-06-12 00:21:47,747: INFO/MainProcess] beat: Starting...
[2019-06-12 00:21:48,088: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
celery beat v4.3.0 (rhubarb) is starting.
__    -    ... __   -        _
LocalTime -> 2019-06-12 00:21:47
Configuration ->
    . broker -> redis://localhost:6379//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)
celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/apps.py", line 34, in ready
    print(page)
NameError: name 'page' is not defined
celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/apps.py", line 34, in ready
    print(page)
NameError: name 'page' is not defined
celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/apps.py", line 34, in ready
    print(page)
NameError: name 'page' is not defined
celery beat v4.3.0 (rhubarb) is starting.
Traceback (most recent call last):
  File "/home/mwa_env/bin/celery", line 10, in <module>
    sys.exit(main())
  File "/home/mwa_env/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
    _main()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 302, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 386, in handle_argv
    return self(*args, **options)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/base.py", line 252, in __call__
    ret = self.run(*args, **kwargs)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/bin/beat.py", line 109, in run
    return beat().run()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 79, in run
    self.init_loader()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/apps/beat.py", line 128, in init_loader
    self.app.loader.init_worker()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 114, in init_worker
    self.import_default_modules()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/loaders/base.py", line 108, in import_default_modules
    raise response
  File "/home/mwa_env/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 84, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 122, in validate_models
    self.django_setup()
  File "/home/mwa_env/lib/python3.6/site-packages/celery/fixups/django.py", line 118, in django_setup
    django.setup()
  File "/home/mwa_env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/mwa_env/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/home/website-build/mywealthanalyst_django/MWA_webapp/apps.py", line 34, in ready
    print(page)
NameError: name 'page' is not defined
[2019-06-12 11:27:29,762: INFO/MainProcess] beat: Starting...
[2019-06-12 11:27:29,811: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
[2019-06-12 11:30:00,000: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
[2019-06-12 11:35:00,073: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
[2019-06-12 11:40:00,037: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
[2019-06-12 11:45:00,088: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
[2019-06-12 11:50:00,092: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
celery beat v4.3.0 (rhubarb) is starting.
__    -    ... __   -        _
LocalTime -> 2019-06-12 11:27:29
Configuration ->
    . broker -> redis://localhost:6379//
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)
[2019-06-12 11:53:56,359: INFO/MainProcess] beat: Starting...
[2019-06-12 11:55:00,009: INFO/MainProcess] Scheduler: Sending due task update_live_prices (update_live_prices)
